"""Seed training data for the FinAnalytix transaction classifier.

Labels match the category slugs seeded in the PostgreSQL database:
  food-dining | transport | social | entertainment | utilities |
  health      | education | clothing | rent-housing | savings  | other

Merchant names, M-PESA descriptions, POS receipts, and bank statement
entries typical of young Kenyans are used to give the model broad coverage.
"""
from __future__ import annotations

# Each tuple is (description_text, category_slug).
TRAINING_SAMPLES: list[tuple[str, str]] = [
    # ── food-dining ──────────────────────────────────────────────────────
    ("Java House coffee", "food-dining"),
    ("Java House Westgate", "food-dining"),
    ("KFC Nairobi", "food-dining"),
    ("KFC Sarit Centre", "food-dining"),
    ("Chicken Inn", "food-dining"),
    ("Pizza Inn delivery", "food-dining"),
    ("Dominos Pizza", "food-dining"),
    ("Nakumatt groceries", "food-dining"),
    ("Carrefour supermarket food", "food-dining"),
    ("Naivas supermarket", "food-dining"),
    ("Quickmart shopping food", "food-dining"),
    ("Tuskys food", "food-dining"),
    ("Zucchini green grocers", "food-dining"),
    ("Mama Ngina restaurant", "food-dining"),
    ("Cafe Deli", "food-dining"),
    ("Dormans coffee", "food-dining"),
    ("Artcaffe brunch", "food-dining"),
    ("galito's chicken", "food-dining"),
    ("smokey's bbq", "food-dining"),
    ("soup kitchen lunch", "food-dining"),
    ("mandazi from mama", "food-dining"),
    ("ugali and sukuma wiki", "food-dining"),
    ("githeri lunch", "food-dining"),
    ("chapati and stew", "food-dining"),
    ("nyama choma", "food-dining"),
    ("mutura snack", "food-dining"),
    ("kenchic chicken", "food-dining"),
    ("pizza delivery", "food-dining"),
    ("food delivery glovo", "food-dining"),
    ("uber eats order", "food-dining"),
    ("jumia food delivery", "food-dining"),
    ("buy groceries market", "food-dining"),
    ("vegetable kiosk", "food-dining"),
    ("bread and milk", "food-dining"),
    ("eggs and flour", "food-dining"),
    ("cooking gas refill", "food-dining"),
    ("lunch cafeteria", "food-dining"),
    ("campus canteen meal", "food-dining"),
    ("mess hall payment", "food-dining"),
    ("snacks vending machine", "food-dining"),
    ("soda and chips", "food-dining"),
    ("midnight snack", "food-dining"),
    ("supermarket weekly shop", "food-dining"),
    ("grocery top up", "food-dining"),
    ("fast food meal", "food-dining"),
    ("restaurant dinner", "food-dining"),
    ("breakfast cafe", "food-dining"),
    ("tea and mandazi", "food-dining"),
    ("mutura and soda", "food-dining"),
    ("shawarma wrap", "food-dining"),
    ("samosa and juice", "food-dining"),

    # ── transport ────────────────────────────────────────────────────────
    ("Bolt ride", "transport"),
    ("Uber trip", "transport"),
    ("Uber fare", "transport"),
    ("Little cab ride", "transport"),
    ("InDrive ride", "transport"),
    ("matatu fare", "transport"),
    ("bus fare CBD", "transport"),
    ("boda boda ride", "transport"),
    ("tuk tuk fare", "transport"),
    ("taxi cab", "transport"),
    ("NTSA motor vehicle levy", "transport"),
    ("KBS bus Nairobi", "transport"),
    ("Mombasa bus ticket", "transport"),
    ("Easy Coach ticket", "transport"),
    ("Modern Coast bus", "transport"),
    ("night bus Nairobi Mombasa", "transport"),
    ("petrol station shell", "transport"),
    ("BP petrol fill", "transport"),
    ("fuel fill up", "transport"),
    ("Kenya Railways SGR", "transport"),
    ("Madaraka Express ticket", "transport"),
    ("parking fee NPC", "transport"),
    ("parking token CBD", "transport"),
    ("vehicle service", "transport"),
    ("mechanic service car", "transport"),
    ("insurance motor vehicle", "transport"),
    ("car wash", "transport"),
    ("airport taxi", "transport"),
    ("airport transfer", "transport"),
    ("ferry crossing", "transport"),
    ("commute fare", "transport"),
    ("train ticket", "transport"),
    ("stage bus", "transport"),
    ("ride share", "transport"),
    ("route 58 matatu", "transport"),

    # ── social ───────────────────────────────────────────────────────────
    ("Alchemist bar Westlands", "social"),
    ("Havana club night", "social"),
    ("B-Club party", "social"),
    ("Mercury lounge", "social"),
    ("Brew Bistro drinks", "social"),
    ("friends night out", "social"),
    ("birthday party venue", "social"),
    ("graduation dinner", "social"),
    ("celebration dinner friends", "social"),
    ("drinks with friends", "social"),
    ("clubbing Friday night", "social"),
    ("cocktails happy hour", "social"),
    ("bottle service lounge", "social"),
    ("beer at bar", "social"),
    ("whiskey club", "social"),
    ("wine at restaurant", "social"),
    ("brunch with friends", "social"),
    ("sundowner party", "social"),
    ("rooftop bar night", "social"),
    ("farewell party", "social"),
    ("welcome party drinks", "social"),
    ("house party supplies", "social"),
    ("team outing lunch", "social"),
    ("work social event", "social"),
    ("date night restaurant", "social"),
    ("anniversary dinner out", "social"),
    ("nairobi social club", "social"),
    ("night out Nairobi", "social"),
    ("weekend hangout", "social"),
    ("friends gathering food", "social"),

    # ── entertainment ────────────────────────────────────────────────────
    ("IMAX cinema Westgate", "entertainment"),
    ("Century Cinemax ticket", "entertainment"),
    ("movie ticket cinema", "entertainment"),
    ("Netflix subscription", "entertainment"),
    ("Showmax subscription", "entertainment"),
    ("Spotify Premium", "entertainment"),
    ("YouTube Premium", "entertainment"),
    ("DStv subscription", "entertainment"),
    ("DSTV renewal", "entertainment"),
    ("Canal+ subscription", "entertainment"),
    ("Azam TV renewal", "entertainment"),
    ("DAZN sports streaming", "entertainment"),
    ("PlayStation Store purchase", "entertainment"),
    ("Xbox Live Gold", "entertainment"),
    ("gaming purchase Steam", "entertainment"),
    ("in-app purchase game", "entertainment"),
    ("concert ticket Carnivore", "entertainment"),
    ("standup comedy show", "entertainment"),
    ("live music event", "entertainment"),
    ("karaoke night out", "entertainment"),
    ("bowling alley", "entertainment"),
    ("escape room booking", "entertainment"),
    ("laser tag", "entertainment"),
    ("theme park entry", "entertainment"),
    ("zoo entry ticket", "entertainment"),
    ("museum entry fee", "entertainment"),
    ("fiction novel book", "entertainment"),
    ("kindle book purchase", "entertainment"),
    ("magazine subscription", "entertainment"),
    ("gaming subscription", "entertainment"),

    # ── utilities ────────────────────────────────────────────────────────
    ("KPLC electricity token", "utilities"),
    ("Kenya Power prepaid token", "utilities"),
    ("electricity bill prepaid", "utilities"),
    ("KPLC postpaid bill", "utilities"),
    ("Nairobi Water bill", "utilities"),
    ("water token prepaid", "utilities"),
    ("internet Safaricom Home", "utilities"),
    ("Zuku internet bill", "utilities"),
    ("JTL Faiba broadband", "utilities"),
    ("Telkom broadband internet", "utilities"),
    ("wifi subscription monthly", "utilities"),
    ("Safaricom airtime top-up", "utilities"),
    ("airtime recharge", "utilities"),
    ("data bundles buy", "utilities"),
    ("internet bundles Airtel", "utilities"),
    ("mobile data top up", "utilities"),
    ("Safaricom Fiber monthly", "utilities"),
    ("garbage collection fee", "utilities"),
    ("estate service charge", "utilities"),
    ("landline phone bill", "utilities"),
    ("pay TV antenna", "utilities"),

    # ── health ───────────────────────────────────────────────────────────
    ("Aga Khan Hospital", "health"),
    ("Nairobi Hospital bill", "health"),
    ("MP Shah clinic", "health"),
    ("doctor consultation fee", "health"),
    ("pharmacy drugs", "health"),
    ("Goodlife pharmacy", "health"),
    ("Haltons pharmacy", "health"),
    ("lab test blood", "health"),
    ("blood test results", "health"),
    ("dental appointment", "health"),
    ("eye check optician", "health"),
    ("physiotherapy session", "health"),
    ("gym membership monthly", "health"),
    ("Ryka gym", "health"),
    ("fitness club subscription", "health"),
    ("NHIF contribution monthly", "health"),
    ("medical insurance premium", "health"),
    ("health insurance payment", "health"),
    ("vitamins supplement", "health"),
    ("vaccine clinic", "health"),
    ("mental health therapy", "health"),
    ("counselling session", "health"),
    ("yoga class fee", "health"),
    ("wellness centre", "health"),
    ("chemist prescription", "health"),

    # ── education ────────────────────────────────────────────────────────
    ("university fee payment", "education"),
    ("HELB loan repayment", "education"),
    ("HELB disbursement income", "education"),
    ("school fees term", "education"),
    ("college tuition fee", "education"),
    ("exam registration fee", "education"),
    ("KNEC exam fee", "education"),
    ("KASNEB registration", "education"),
    ("textbooks purchase", "education"),
    ("stationery supplies school", "education"),
    ("printing lecture notes", "education"),
    ("library fine", "education"),
    ("Coursera subscription", "education"),
    ("Udemy course purchase", "education"),
    ("LinkedIn Learning subscription", "education"),
    ("online course fee", "education"),
    ("coding bootcamp", "education"),
    ("AWS certification exam", "education"),
    ("Google certification fee", "education"),
    ("professional development", "education"),
    ("workshop training fee", "education"),
    ("seminar registration", "education"),

    # ── clothing ─────────────────────────────────────────────────────────
    ("Mr Price clothes", "clothing"),
    ("Woolworths fashion", "clothing"),
    ("Jet store outfit", "clothing"),
    ("Giordano shirt", "clothing"),
    ("H&M clothing", "clothing"),
    ("Zara outfit", "clothing"),
    ("Jumia fashion order", "clothing"),
    ("Kilimall clothes", "clothing"),
    ("Temu clothing haul", "clothing"),
    ("second hand clothes mitumba", "clothing"),
    ("shoe purchase", "clothing"),
    ("sneakers Adidas", "clothing"),
    ("Nike shoes", "clothing"),
    ("sandals purchase", "clothing"),
    ("belt and wallet", "clothing"),
    ("handbag purchase", "clothing"),
    ("suit tailoring", "clothing"),
    ("dress made tailor", "clothing"),
    ("fabric purchase material", "clothing"),
    ("official shirt and trouser", "clothing"),
    ("underwear and socks", "clothing"),
    ("jacket coat", "clothing"),
    ("fashion accessories", "clothing"),

    # ── rent-housing ─────────────────────────────────────────────────────
    ("rent payment landlord", "rent-housing"),
    ("monthly rent M-PESA", "rent-housing"),
    ("house rent", "rent-housing"),
    ("bedsitter rent", "rent-housing"),
    ("single room rent", "rent-housing"),
    ("apartment rent monthly", "rent-housing"),
    ("estate rent Kilimani", "rent-housing"),
    ("caretaker service fee", "rent-housing"),
    ("estate management fee", "rent-housing"),
    ("furnishing sofa set", "rent-housing"),
    ("bed mattress purchase", "rent-housing"),
    ("household appliances fridge", "rent-housing"),
    ("kitchen utensils", "rent-housing"),
    ("curtains and blinds", "rent-housing"),
    ("house cleaning service", "rent-housing"),
    ("plumber fee repair", "rent-housing"),
    ("electrician repair home", "rent-housing"),
    ("painting house walls", "rent-housing"),
    ("security deposit new house", "rent-housing"),
    ("rent deposit landlord", "rent-housing"),

    # ── savings ──────────────────────────────────────────────────────────
    ("Sacco deposit monthly", "savings"),
    ("SACCO contribution", "savings"),
    ("merry-go-round contribution", "savings"),
    ("table banking deposit", "savings"),
    ("M-Shwari lock savings", "savings"),
    ("KCB M-PESA savings", "savings"),
    ("Equity bank savings", "savings"),
    ("fixed deposit FD", "savings"),
    ("investment fund deposit", "savings"),
    ("NSE share purchase", "savings"),
    ("Treasury bill T-bill", "savings"),
    ("goal savings transfer", "savings"),
    ("savings account transfer", "savings"),
    ("building fund contribution", "savings"),
    ("emergency fund save", "savings"),
    ("chama contribution monthly", "savings"),
    ("investment M-Akiba", "savings"),
    ("pension NSSF contribution", "savings"),
    ("unit trust deposit", "savings"),

    # ── other ────────────────────────────────────────────────────────────
    ("ATM withdrawal cash", "other"),
    ("bank charge fee", "other"),
    ("wire transfer fee", "other"),
    ("M-PESA transfer charge", "other"),
    ("mobile money fee", "other"),
    ("bank statement fee", "other"),
    ("miscellaneous expense", "other"),
    ("hardware store", "other"),
    ("printing photocopy shop", "other"),
    ("gifts for family", "other"),
    ("donation charity", "other"),
    ("church offering tithe", "other"),
    ("mosque sadaka contribution", "other"),
    ("harambee contribution", "other"),
    ("money sent home upcountry", "other"),
    ("family remittance", "other"),
    ("barber haircut", "other"),
    ("salon hair treatment", "other"),
    ("beauty parlour", "other"),
    ("nail salon", "other"),
    ("spa massage", "other"),
    ("pet food", "other"),
    ("vet fee animal", "other"),
    ("flowers bouquet", "other"),
    ("stationary office supplies", "other"),
    ("DHL courier delivery", "other"),
    ("G4S parcel delivery", "other"),
    ("money transfer", "other"),
]
